### ISSUE TITLE
2003page and old browsers.

### ISSUE THREAD

**Issue by PF94** [ChazizTech/2003page#37]
Before 2003page relaunched and got redesigned to look more modern. Old browsers (at least, the late-2000s ones after the "sidebar" thing) fully supported 2003page, thanks to 2003page (at the time) not allowing HTML5 and CSS3.
Firefox 3.6 | Firefox 81.0.2
-------|--------
![image](https://user-images.githubusercontent.com/45898787/96385659-51fe8000-1163-11eb-9cd8-9311a021204d.png)| ![image](https://user-images.githubusercontent.com/45898787/96385687-840fe200-1163-11eb-9a52-1ab138d35055.png)

However, ever since Bootstrap got added into the main page of 2003page, support for old browser were lost.

Firefox 3.6 | Firefox 81.0.2
-------|--------
![image](https://user-images.githubusercontent.com/45898787/96385716-adc90900-1163-11eb-80e0-fea659b05c4c.png)| ![image](https://user-images.githubusercontent.com/45898787/96385733-bb7e8e80-1163-11eb-96fd-5f224ea3ba23.png)

This isn't a issue for both the HTTPS-only TWTACCT, and the fake nostalgia-based RetroSite, however on 2003page, it is a broken.

And no, we will not rollback to what the main page was shortly after the relaunch (when buttons were ditched in place of hyperlinks).

My idea was that old unsupported browsers would get redirected to a specialized legacy version of the main page (and contributing once it gets complete), or we just forget all of this shit and just invalidate any issues regarding old browsers.

**Comment by Upwader** [comment]
we shouldnt support old browsers in the first place
why: imagine using firefox 3 and Netscape in 2020, the heck you expect to do on there??

**Comment by PF94** [comment]
there's probably going to be that one person on the web who is obessed with old browsers and tries to goes on 2003page and says "O THSI SIST SHEIT"

**Comment by forkiesassds** [comment]
copy the code i wrote in may

**Comment by PF94** [comment]
(reply to hidden comment)
the "may" code was about the gradients... have you checked 2003page after it came back 5 months later?

**Comment by forkiesassds** [comment]
> (reply to hidden comment)
> the "may" code was about the gradients... have you checked 2003page after it came back 5 months later?

yes, bootswatch

**Comment by PF94** [comment]
well

the only way i know of for fixing 2003page for old browsers is to make old browsers redirect to a different index.html, i'm considering ethier making a new index or just copying a really old index.html and just modifying that.

**Comment by PF94** [comment]
so, i've been considering if i should ethier

1. use the IE7 era (i have a snapshot of index.html from april)
2. use something from 2019 (http://2003page.retrosite.ga/10/index.htm for example)

**Comment by PF94** [comment]
I am closing this issue as it has to do with index, which seems to be where the majority of 2003page's updates occur.

Nobody browses 2003page with a old browser, same thing goes for the HTTPS-only TWTACCT and the using-fake-nostalgia retrosite.

This is how 2003page looks on Firefox 3.6.22.

![image](https://user-images.githubusercontent.com/45898787/97378781-94c60380-1899-11eb-8487-f662ecea9ee5.png)

We will not be fixing the main page just to support 2003page.

**Comment by PF94** [comment]
We could add a legacy main page if one clicks the soon-to-be-added 88x31 button, but that's pretty much about it.

Also, the legacy main page would have been from the end of the IE7 era, from about early-October 2020.

**Comment by thebirdwashere** [comment]
heres a response to those people who would complain about support, JUST USE THE HYPERLINKS! its not like every single subsite uses bootstrap, just the main page. Honestly if you want i could build a legacy version, but how would we implement redirection on it?
EDIT: Looks like legacy is here, now anyone who sees this and is mad about support, CLICK THE 2003PAGE BUTTON.

**Comment by PF94** [comment]
Legacy 2003page is pretty much a modified snapshot of the early-October 2003page (before any bootstrap was added).

It has the special CSS, but it may be updated to have the slightly newer project Phoenix special CSS.
