### ISSUE TITLE
404's broken.

### ISSUE THREAD

**Issue by PF94** [ChazizTech/2003page#38]
![image](https://user-images.githubusercontent.com/45898787/97379736-d48dea80-189b-11eb-9d40-0c0d8743e469.png)

**Comment by thebirdwashere** [comment]
Gonna try to fix this now.

**Comment by thebirdwashere** [comment]
Well looks like the domain of the sub folder where the 404 assets are was spelled errors, even though that folder doesn't exist, the folder is actually error, removed the s and it started working again. Should be working for everyone soon.
