### ISSUE TITLE
2003page 2021 Redesign

### ISSUE THREAD

**Issue by PF94** [ChazizTech/2003page#41]
With the mistake that was bootstrapping 2003page, in a half-baked effort. We have decided to redo the redesign, this time keeping the layout of the Bootstrapped main page. This will also get rid of the need of the legacy main page.

# My Ideas
## Special CSS for 2021 2003page.
Bootstrapped 2003page got rid of the "Special CSS", some code that changed the gradient of the main page to celebrate something, even MessengerGeekia's birthday for some reason. I want that to be reimplemented, even if that includes getting rid of "dark mode" for some days. Whist this could be another case of overengineering, I honestly don't care.

## Do we really need the flag counter?
While the Flag Counter could be useful for looking at 2003page views, it is inefficient in a way, Adblockers block it as it could be seen as some "tracking service".

![image](https://user-images.githubusercontent.com/45898787/98306698-5237b180-1f92-11eb-89b0-84349b4f7a81.png)

It also has the flaw of being a relic of 2019 2003page, which is too simillar to 2003page's rival, Retrosite. However, removing this will make 2003page look weird as it's main page won't be tall.

## Subsites list broken on old browsers.
Fuck old browsers.

## Footer should have a different color.
But it's going to look like ass unless if we bloat main page with vertical space... yeah no.

**Comment by forkiesassds** [comment]
Regarding special CSS:
What should be there?

**Comment by PF94** [comment]
same thing that was on legavy

**Comment by forkiesassds** [comment]
> 
> 
> same thing that was on legavy

added, might need some improvement...
