### ISSUE TITLE
Fix 10 Maintainability issues in mainpage.css

### ISSUE THREAD

**Issue by PF94** [ChazizTech/2003page#8]
[CodeFactor](https://www.codefactor.io/repository/github/chaziztech/2003page/overview/master) found multiple issues:

#### Unexpected duplicate selector &quot;.clean-block.clean-post .post-body&quot;, first used at line 9332 (no-duplicate-selectors)
[mainpage.css:9338
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L9338)
#### Unexpected duplicate selector &quot;.clean-block.clean-cart .items .product&quot;, first used at line 8841 (no-duplicate-selectors)
[mainpage.css:8855
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L8855)
#### Unexpected duplicate selector &quot;.baguetteBox-button&quot;, first used at line 8179 (no-duplicate-selectors)
[mainpage.css:8607
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L8607)
#### Unexpected duplicate selector &quot;.navbar-expand&gt;.container, .navbar-expand&gt;.container-fluid&quot;, first used at line 3493 (no-duplicate-selectors)
[mainpage.css:3508
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L3508)
#### Unexpected duplicate selector &quot;.dropleft .dropdown-toggle:before&quot;, first used at line 2549 (no-duplicate-selectors)
[mainpage.css:2561
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L2561)
#### Unexpected duplicate selector &quot;.dropright .dropdown-toggle:after&quot;, first used at line 2519 (no-duplicate-selectors)
[mainpage.css:2532
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L2532)
#### Unexpected duplicate selector &quot;pre&quot;, first used at line 146 (no-duplicate-selectors)
[mainpage.css:398
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L398)
#### Unexpected duplicate selector &quot;hr&quot;, first used at line 64 (no-duplicate-selectors)
[mainpage.css:317
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L317)
#### Unexpected duplicate &quot;display&quot; (declaration-block-no-duplicate-properties)
[mainpage.css:2547
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L2547)
#### Unexpected duplicate &quot;text-decoration&quot; (declaration-block-no-duplicate-properties)
[mainpage.css:80
](https://www.codefactor.io/repository/github/chaziztech/2003page/source/master/mainpage.css#L80)

**Comment by PF94** [comment]
pretty sure this is because of blue's css

**Comment by Upwader** [comment]
Penis coc

**Comment by bluethefoxofficial** [comment]
this is because of the code i used for this which much cant be done due to the issue of the smallest changes will break.

**Comment by PF94** [comment]
the fucking CSS is too large

and it's only utilized on 1 page

ONE FUCKING PAGE
